### ISSUE TITLE
C# library documentation from XML tags

### ISSUE THREAD

**Issue by davidandl** [kulibali/ironmeta#10]
The C# library contains lots of useful documentation, but this is not visible when debugging a target program. Is it possible to distribute documentation built from the tags, or a perhaps a debug version of the software in which the source code can be browsed?

**Comment by kulibali** [comment]
Symbols and source are now at symbolsource.org; see http://www.symbolsource.org/Public/Home/VisualStudio for how to set up Visual Studio to get them when debugging.

**Comment by davidandl** [comment]
That sounds good, but wouldn't just distributing a PDB work as well?
I guess my main need was for some IntelliSense, with those XML header comments and not just the symbols. Or API docs built form the source.

**Comment by davidandl** [comment]
This link is about what I was hoping for: http://stackoverflow.com/questions/13750771/intellisense-not-showing-xmldoc-for-referenced-dll.
I'll see if I can get it to work (now that I know how to build it).

**Comment by davidandl** [comment]
Seems to work fine. Set the option for XML docs, copy the XML file along with the DLL. IJW.

**Comment by dhowe** [comment]
+1
also, link above (http://www.symbolsource.org/Public/Home/VisualStudio ) is broken...
