### ISSUE TITLE
Add an MSBuild task

### ISSUE THREAD

**Issue by JayBazuzi** [kulibali/ironmeta#12]
An MSBuild task would make it easy to add IronMeta to the build process, including understanding dependencies between .ironmeta and generated .cs.

This would avoid the problem where someone changes (for example) the name of an AST node class, but forgets to rerun ironmeta.

Here's a first stab at an MSBuild Task:

```
using IronMeta.Generator;
using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;

public class IronMetaTask : Task
{
    public override bool Execute()
    {
        var result = CSharpShell.Process(Input, Output, Namespace, Force);

        if (result.Success)
        {
            return true;
        }
        else
        {
            Log.LogError(result.Error);

            return false;
        }
    }

    public bool Force { get; set; }

    public string Namespace { get; set; }

    public string Output { get; set; }

    [Required]
    public string Input { get; set; }
}
```

**Comment by JayBazuzi** [comment]
reference on how to use this: https://mhut.ch/journal/2015/06/30/build_time_code_generation_msbuild

**Comment by kulibali** [comment]
I'll look into this.  Sorry it took so long . . . turns out I had turned off emails from github, so i didn't see this until just now.

**Comment by kulibali** [comment]
Are you running from the command-line?  If you are in Visual Studio, there is already an extension (https://visualstudiogallery.msdn.microsoft.com/73263c7c-319f-4f9e-a05a-b493094a4eb0) that provides a generator.  Install this and set the "Custom Tool" property of your .ironmeta file to "IronMetaGenerator".

**Comment by JayBazuzi** [comment]
Yes command line; specifically in AppVeyor.

We had a problem where we moved a class to a different namespace, but didn't update the .ironmeta file to match. We didn't notice until the next time we edited the .ironmeta file.

Regenerating on build would have caught that in CI.
