### ISSUE TITLE
Can't pass constructed rules as arguments to rules

### ISSUE THREAD

**Issue by arlobelshee** [kulibali/ironmeta#13]
Given a rule that takes another as an argument:

```
Statement :indentation = indentation SomeOtherThing;
```

I would like to call this in some way that allows me to compute on the value `:indentation`. For example:

```
BlockBody :indentation = Statement('\t' indentation)*:statements;
// or
AlternateBlockBodyRule :indentation = Statement(Indent(indentation))*:statements;
Indent :indentation = '\t' indentation;
```

Neither of these work. The generator fails to parse my intent, and just passes `null` as the argument to `Statement`, which obviously fails.

**Comment by kulibali** [comment]
Looks like I meant to add this functionality at one time but didn't get around to it.  I'll take a look.

**Comment by kulibali** [comment]
New release 4.3.0 contains the ability to pass arbitrary patterns as arguments to rules, so both your examples should work.
