### ISSUE TITLE
expected eof or identbody

### ISSUE THREAD

**Issue by furesoft** [kulibali/ironmeta#17]
hi,

i have the followng problem: expected EOL or IdentBody on line 14 the str part.
when i comment out the values part compiles. so what is wrong with my regex, its valid regex
my grammar:

`
using System;
using System.Linq;
using IronMeta.Matcher;

ironmeta Function<char, string>
{
    Expression = name "(" args ")";
    
    name = /[_a-zA-Z][_a-zA-Z0-9]*/;
	args = value | value ",";
	value = str | integer | floating | hex;

	//values
    str = /"((?:\\.|[^"\\])*)"/;
	integer = /[-+]?[0-9]+/;
	hex = /0x[0-9A-Fa-f]+/;
	floating = /[-+]?[0-9]*\.?[0-9]*/;
}
`

what do i wrong?

**Comment by kulibali** [comment]
The regexps that IronMeta uses are not standard .NET regexps.  They use the Verophyle.Regexp library.  You can find the grammar for these at https://github.com/verophyle/regexp/blob/master/Regexp/RegexpParser.ironmeta

**Comment by furesoft** [comment]
and why its not uing standard .net regex?

**Comment by kulibali** [comment]
Because the standard library ones do not use DFAs, and do not allow incremental test.  This will work for you (you have to escape '-' and '+'):

  using System;
  using System.Linq;
  using IronMeta.Matcher;

  ironmeta Function<char, int>
  {
    Expression = name "(" args ")";

    name = /[_a-zA-Z][_a-zA-Z0-9]*/;
    args = value | value ",";
    value = str | integer | floating | hex;

    //values
    str = /\"(([\\\"]|.)*)\"/;
    integer = /[\-\+]?[0-9]+/;
    hex = /0x[0-9A-Fa-f]+/;
    floating = /[\-\+]?[0-9]*\.?[0-9]*/;
  }

**Comment by furesoft** [comment]
thks but the string producton wont be escaped correctly in generated source, whe i remove @ before the generatet string it works
