### ISSUE TITLE
Calculator Example

### ISSUE THREAD

**Issue by immortalus** [kulibali/ironmeta#20]
a) The calculator example is broken...

Will successfully parse '5+3' giving the answer '8'...

But will also successfully parse '5+' giving the answer '5'.

The parser returns a 'MatchResult' with an error condition 'not enough arguments;expected DecimalDigit or WS' which is correct but the 'Success' value is set to 'true' and not 'false'.

The match is not a success so why is it being reported as a success???

b) Also for '5+3' there is also the same error condition... just a different errorindex...

c) As an aside: Why is there no parse tree being constructed and returned as part of the 'MatchResult'? Does this have to be constructed manually using actions?

**Comment by kulibali** [comment]
a) The matcher will match as much as possible, and no more.  Observe that the `NextIndex` property of the result for "5+" is `1`, not `2`, which indicates that the matcher only matched 1 character, not 2.

If you want to make sure to match to the end of the input, add a rule `EOF = ~.;` and use it at the end of your topmost rule.  You can see an example of this in `Source/Library/Generator/Parser.ironmeta`.

The error condition is simply the latest error encountered in any of the choices of the grammar.  The presence of an error does not mean that the match as a whole failed.

c) No parse tree is explicitly constructed; you will indeed need to construct one using actions.
