### ISSUE TITLE
Integrating IronMetaGenerate task in Visual Studio

### ISSUE THREAD

**Issue by dhowe** [kulibali/ironmeta#21]
Can you be more specific about how to integrate this in Visual Studio 2017?  Perhaps a step-by-step?

> IronMeta.Library.dllcontains an MsBuild task called "IronMetaGenerate". A simple example of how to use this:
```
      <UsingTask TaskName="IronMetaGenerate" AssemblyFile="path_to\IronMeta.Library.dll" />
      <Target Name="BeforeBuild">
        <IronMetaGenerate Input="MyParser.ironmeta" Output="MyParser.g.cs" Namespace="MyNamespace" Force="true" />
      </Target>
```

**Comment by dhowe** [comment]
I've tried a bunch of different ways to configure things, but this is latest error I get:

/Projects/Iron/Test/Test.csproj(5,5): Error MSB4062: The "IronMetaGenerate" task could not be loaded from the assembly /Projects/Iron/Test/IronMeta.Library.dll.  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. (MSB4062) (Test)

**Comment by kulibali** [comment]
I'm afraid I have not had time to update things for VS2017.

**Comment by dhowe** [comment]
I'm happy to run it any way possible, the problem is I am on OS X, so I don't have the VS extension and I can't run the exe... :/

**Comment by dhowe** [comment]
Any other options?

**Comment by kulibali** [comment]
Is the .exe not getting built correctly for .NET Core?  Why can't you run it on OSX?

**Comment by kulibali** [comment]
Er, I mean can you run `dotnet IronMeta.dll` in OSX?

**Comment by dhowe** [comment]
I haven't been able to build it. When I open the project in VS2017, I get the following error for the extension:

<img width="597" alt="screen shot 2018-09-22 at 1 30 10 pm" src="https://user-images.githubusercontent.com/737638/45913760-e9e9ec80-be6b-11e8-8846-fd1f41a38484.png">

When I delete the extension project and try to build the rest, I get:

<img width="1166" alt="screen shot 2018-09-22 at 1 30 41 pm" src="https://user-images.githubusercontent.com/737638/45913766-f53d1800-be6b-11e8-9f9e-7b24c091cbdd.png">

**Comment by dhowe** [comment]
Ok, so I've been able to build the App and Lib project after a few steps:
1. Create a new .NET Framework 4.6.2 project
2. Copy in the source for IronMeta App and Lib
3. Edit their .csproj types to be 'net462'
4. Copy the generated .snk  file to where it is expected
4. Restore nuget packages
5. Build

The dll and the exe are generated, but I still cannot run the .exe ("cannot execute binary file: Exec format error")


However I still get an error

**Comment by kulibali** [comment]
Now I'm confused.  Are you on Windows or OSX?  I was under the impression that you can only build .NET core on OSX...  I assume from your latest that you are building on Windows with VS2017?  Is that the case?

**Comment by dhowe** [comment]
OS X 10.13.5
B/c its not .NET core the generated application won't run from the terminal

**Comment by kulibali** [comment]
The project files are set up (at least for Windows) to generate output for `net462`, `net471` and `netcoreapp2.0`.  When I build them on Windows I get a folder, e.g. `Source\IronMeta.App\bin\Debug\netcoreapp2.0` that contains a file `IronMeta.App.dll`.  I can run this using `dotnet IronMeta.App.dll`, which is just like running the .NET Framework exe.

I'm afraid I've never used VS for Mac, so I don't know if it should do the same thing.

**Comment by kulibali** [comment]
It seems that extensions built for VS for Windows will not work on VS for Mac.
