### ISSUE TITLE
Double Quotes in Regex

### ISSUE THREAD

**Issue by begrs** [kulibali/ironmeta#25]
Hi, I have trouble getting a Regex to work which should match double quotes.

Example:  CustomString = /[^"]*/;  -> it should match any char from one " to the other ". (Note that the surrounding double quotes are in the parent expression.  This actually just matches everything that is not a double quote)

As far as I understand you are usinng https://github.com/verophyle/regexp for your regex and marking a regex with /..../  instead of new Regex("...."). This works just fine for everything BUT escaped or not-escaped double quotes. CustomString = /[^\"]*/; this also does not work and will cause a syntax error (i.e. EOL message).

This also does not work:
CustomString = /[^\u0022]*/;     // this encodes unicode double quotes
or
CustomString = /[^\u{0022}]*/;     // this encodes unicode double quotes

I think letting the user escape the double quotes would be the more consistent approach, or if that is not an option, especially list the double quotes and how to work around them in a regex in the documentation.

**Comment by kulibali** [comment]
This is fixed in version 4.4.2, which should be on NuGet in a few minutes.
