### ISSUE TITLE
Unit testing example?

### ISSUE THREAD

**Issue by darrenstarr** [kulibali/ironmeta#27]
I am porting my project to .NET Standard and it is important to me to be able to unit test each grammar rule individually.

Can you please provide an example of calling a specific rule within a full grammar and verifying its output using either XUnit or similar?

Thanks in advance!

**Comment by kulibali** [comment]
There are many unit tests (using VSTest) in the `IronMeta.Tests` project.  For an example of testing individual rules, you can take a look at `LeftRecursionTests.cs` (https://github.com/kulibali/ironmeta/blob/master/Source/IronMeta.Tests/Matcher/LeftRecursionTests.cs)
