### ISSUE TITLE
extension does not work

### ISSUE THREAD

**Issue by furesoft** [kulibali/ironmeta#28]
i want to use your generator but nothing happens. i have created a file Grammar.ironmeta with Custom Tool IronMetaGenerator but nothing happens

**Comment by kulibali** [comment]
It works for me; please provide more details about your setup and the steps you took.

For example, just now I did the following:

- Installed the IronMeta extension in Visual Studio 19 (16.3.6).
- Created a new .NET Core command line project.
- Created a file called `Grammar.ironmeta` in that project with the following content: 

    ironmeta Grammar<char, int> : Matcher<char, int>
    {
        Abc = "abc";
        Def = "def";
        SP = " ";
        Phrase = Abc SP? Def;
    }

- In the properties for `Grammar.ironmeta`, I set the Custom Tool property to `IronMetaGenerator`.  This then created a file `Grammar.g.cs` in my project directory, which defined a class that I could use in my project.

If the `.g.cs` file is not automatically created from your `Grammar.ironmeta` file, try right-clicking on the file in the Solution Explorer and choosing "Run Custom Tool".

**Comment by furesoft** [comment]
i have found the problem. i did: IronMetaGenerate and not IronMetaGenerator.
Could you provie a custom BuildTask so its less confusing
