### ISSUE TITLE
No line positions have been set by the grammar. Parameter name: index

### ISSUE THREAD

**Issue by davidandl** [kulibali/ironmeta#3]
Occurred while developing new grammar. About 150 lines and absolutely no indication of where the problem is or where to start looking.
Some logging would help.

[having difficulty uploading file]

**Comment by kulibali** [comment]
The error "no line positions have been set by the grammar" occurs when you call `MatchState.GetLine()` without adding any line end positions during your parse.  You'll need to add an action to your `EOL` rule to do this before you can call `GetLine()`, e.g.:

  EOL = ('\r' '\n'? | '\n'):nl -> { _memo.Positions.Add(nl.NextIndex); return nl; };

**Comment by davidandl** [comment]
I think you may have misunderstood. This is an error emitted by the IronMeta compiler when parsing a faulty grammar. I assume it means that the grammar for the parser itself has the fault you mention above. It means that you need to add a suitable rule to the IronMeta grammar.
