### ISSUE TITLE
Handling word-level regexes with `.*`

### ISSUE THREAD

**Issue by mikhail-barg** [kulibali/ironmeta#32]
Hi, we are looking towards moving our custom word-level regex engine to IronMeta. Considering that at least for characters IronMeta supports regex-based rules, it seems like it should work out of the box. 

Here's th issue I'm currently looking at. Let's consider the following regex: `.* "test" .*`. It should match all the phrases, containing word `test`, eg. `["test"]`, `["some", "test"]`.
So a naive translation into IronMeta matcher would look like this:
```c#
ironmeta MatcherSpecific<string, bool>: Matcher<string, bool>
{
    Pattern_0 =  .* "test" .*;
    Expression = Pattern_0;
}
```
and it does not match any of the test phrases (giving `error: expected end of file`). This seems somewhat expectable considering the greedy nature of the quantification operators in IronMeta.

So I kinda found two ways to make matcher for this sample regex:

```c#
ironmeta MatcherSpecific<string, bool>: Matcher<string, bool>
{
    Pattern_0 =  "test" .*;
    Pattern_0 =  . Pattern_0;
    Expression = Pattern_0;
}
```
```c#
ironmeta MatcherSpecific<string, bool>: Matcher<string, bool>
{
    Pattern_0 =  (~"test" .)* "test" .*;
    Expression = Pattern_0;
}
```
But it's unclear to me how to generalize these solutions to more complex real-world regex cases. Could you please suggest something?

I wonder if the regular regexes for characters are also working this way in IronMeta?

**Comment by kulibali** [comment]
In order to not be greedy in PEG grammars (PEG grammars are not regexes!) you have to use negative lookahead, as in your second example.  I would do something like this:

    TestToken = "test";
    Token = /\S+/;
    Space = /\s+/;
   PhraseWithTest = Space? (~TestToken Token Space?)* TestToken Space? (Token Space?)*;

**Comment by mikhail-barg** [comment]
Thanks for the answer. I understand that PEG are not regexes :) . What I was looking for was a simplest way to translate existing regexes into IronMeta automatically. 

The problem with lookahead is that It's not clear to me what would it turn into for really complex regexes. 

Meanwhile I also found [this answer on SA](https://stackoverflow.com/a/13945932/376066) which could be a start (if somebody would be looking through this later), but this would not suit my needs as well.

Seems that I'll have to go completely different way. Anyway, thanks for support!

In case
