### ISSUE TITLE
Compiler for grammar installed by NuGet will not run, DLL not in folder

### ISSUE THREAD

**Issue by davidandl** [kulibali/ironmeta#4]
Copying the lib DLL into the folder allows it to run.

**Comment by kulibali** [comment]
Not sure what you mean by this.  Can you provide repro steps, please?  If I do the following:

- Create a new C# project.
- Use the NuGet package manager to install the IronMeta package.
- Add an .ironmeta file and set its custom tool to "IronMetaGenerator"
- Use the generated parser in code.
- Build the project.

All the DLLs needed end up in the project's output directory.

**Comment by kulibali** [comment]
Ah, I see what you mean.  The command-line compiler is missing DLLs.  Fixed in 4.2.1.

**Comment by davidandl** [comment]
Correct.

 

But you cannot run the compiler on its own. If you now try to execute the exe file from the command line, it won’t run.

 

[I did this hoping for some kind of logging/verbose option.]

 

Regards

David M Bennett FACS

  _____  

Andl - A New Database Language - andl.org
